server {
  bind_address = "0.0.0.0"
  bind_port    = "8081"
  trust_domain = "example.org"
  data_dir     = "/tmp/spire-server"
  log_level    = "INFO"

  ca_subject {
    country      = ["US"]
    organization = ["SPIRE Integration Test"]
    common_name  = ""
  }
}

plugins {
  DataStore "sql" {
    plugin_data {
      database_type     = "sqlite3"
      connection_string = "/tmp/spire-server/datastore.sqlite3"
    }
  }

  KeyManager "memory" {
    plugin_data {}
  }

  NodeAttestor "join_token" {
    plugin_data {}
  }
}

health_checks {
  listener_enabled = true
  bind_address     = "0.0.0.0"
  bind_port        = "8080"
  live_path        = "/live"
  ready_path       = "/ready"
}
